[package]
name = "toy_arena"
authors = ["toyboot4e"]
version = "0.1.3"
edition = "2018"
description = "Extensible generational arena for various uses"
license = "MIT"

[dependencies]
derivative = "2.2.0"
smallvec = "1.6.1"
