= `toy_arena`
:toy-arena: https://docs.rs/toy_arena/latest/toy_arena/[toy_arena]
:thunderdome: https://docs.rs/thunderdome/latest/thunderdome/[thunderdome]
:indextree: https://docs.rs/indextree/latest/indextree/[indextree]
:tree: https://docs.rs/toy_arena/latest/toy_arena/tree/index.html[tree]
:miri: https://github.com/rust-lang/miri[miri]
:sb: https://github.com/rust-lang/unsafe-code-guidelines/blob/master/wip/stacked-borrows.md[Stacked Borrows]
:aliasing: https://rust-lang.github.io/unsafe-code-guidelines/glossary.html#aliasing[aliasing]
:ucell: https://doc.rust-lang.org/std/cell/struct.UnsafeCell.html[UnsafeCell]
:no-2: https://github.com/toyboot4e/toy_arena/issues/2[#2]
:no-4: https://github.com/toyboot4e/toy_arena/issues/4[#4]
:no-5: https://github.com/toyboot4e/toy_arena/issues/5[#5]
:ego-tree: https://docs.rs/ego-tree/latest/ego_tree/[ego_tree]
:indextere: https://docs.rs/indextree/latest/indextree/[indextree]

{toy-arena} is a generational arena for my game development.

== Devlog

* Aug 13, 2021
+
I published {toy-arena} on crates.io. It is going to make uses of mutable iterators rather than forcing users to do manual, slot/index-based iteration.

* Aug 14, 2021
+
I changed all `PhantomData<T>` to `PhantomData<fn() -> T>`; see the table in the https://doc.rust-lang.org/nomicon/phantom-data.html[article] in rustonomion .

* Aug 15, 2021
+
I added WIP {tree} support, following the API of {indextree}.

* Aug 21, 2021
+
I wrote some `unsafe` in some projects and it worked, but it was not based on the fundamental knowledge: {aliasing} rules and {ucell}.
+
Borrow checker can be deceieved with `unsafe` and pointer dereferencing, and it can work without any issue at runtime. _But_ breaking the borrow rules at runtime is considered to be *UB* because Rust does optimization based on the analyzed aliasing information. Some examples are `static mut` https://github.com/rust-lang/rust/issues/53639[hazards]. So I removed all the UBs.
+
How do I know if I have UB? {miri} lets me know! It experimentally enforces {aliasing} rules based on {sb}. I tried ~10 examples and got familar with the concept in details (at least in {miri}'s model). Thank you {miri} people!
+
I fixed some of the errors {miri} detected. Fixing ideas can be found in {no-4} and {no-5}.

* Aug 22, 2021
+
I added node removal support for the tree module. It's almost ready!
+
Resetting generations of arena entries does confuse existing entities. If I add *generation of tree*, the operation will be safe, but that would in tern make our generation type fat.

* Aug 23, 2021
+
It turned out `ArenaCell` is not sound. See {no-2},

* Aug 24, 2021
+
I'm fixing the tree API, considering the two routes:

** {ego-tree} route
+
It exposes an explicit root node and makes use of object-oriented API where the tree upgrades `NodeId` to node binding (`NodeRef` or `NodeMut`).

** {indextree} route
+
It puts most of siblings/children linkinig APIs in `NodeId`. `parent.append(child, &mut arena)` reads well to me.
+
I'll follow {indextree} so that `toy_arena::tree` is a bit similar to the arena's API. Also, I don't want an explicit root node as a user actually.

I also tried adding GitHub actions. Does `cargo +nightly miri test` run?

* Aug 25, 2021
+
I added `tree!` macro. The implementation is a bit mess, and debugging was hard, but soon got it!:
+
[source,rust]
----
let tree: Tree<usize> = tree! {
    0,
    1, {
        10,
        11, {
            100,
            101,
        },
        12,
    },
};
----
+
Tips:
* Use https://doc.rust-lang.org/beta/unstable-book/library-features/trace-macros.html[trace_macros] for debugging
* Use `$crate` https://doc.rust-lang.org/reference/macros-by-example.html#hygiene[hygiene]
* Match to `{ .. }` first (with earlier rules) and then `tt` s (in later rules)
* https://rust-lang.github.io/rfcs/3086-macro-metavar-expr.html[3086-macro-metavar-expr - The Rust RFC Book] I've never given it a try though!

